### ISSUE TITLE
Hello, I put the .js into scripts and it simply doesnt work

### ISSUE THREAD

**Issue by Potat0Servers** [gaesa/mpv-autoload#1]
as title, mpv cannot load the files

**Comment by gaesa** [comment]
To help me better understand and address this issue, could you please provide the following information:
1. Program Execution Time: The program requires a certain amount of time to complete its task, approximately 3 seconds for 200 files. If the playlist is accessed immediately after `mpv` initiates the opening of a video or audio file, the playlist may not appear complete. Could you please confirm whether sufficient time was allowed for the program to complete its task?

2. External Command Dependencies: The functionality of this program relies on external commands installed on your machine, specifically `file` and `xdg-mime`. These executables are utilized to determine the file type of all files within a directory, thereby filtering and compiling a comprehensive list of videos and audio files. Could you please confirm whether these commands are installed and accessible by `mpv` on your machine?

3. MPV Behavior: In order to gain a precise understanding of the issue at hand, could you please describe in detail the behavior of `mpv` when it fails to load the files? If possible, could you provide a log or a screenshot of the issue?

4. User Environment and `mpv` Version: The operating system, its version, and the version of `mpv` can sometimes contribute to issues with program functionality. Could you please provide details regarding your operating system type, version, and the version of `mpv` you are using?

**Comment by gaesa** [comment]
This issue might be related the discrepancy between the current working directory and the directory of the media. This difference is causing external commands to be unable to access media files returned by `utils.readdir`. For instance, if you previously ran `mpv dir/foo.mp4`, other media inside the `dir` directory couldn't be loaded into the playlist. However, this should now be fixed with the commit 89bf62a8d44ba02add08bc313bd8c47d90cbf7b7.
